// eslint-disable-next-line
//! It seems like (according to SimpleTuts Youtube Video) the providers are where you include the data you want to use in your components... 
//! ...but it's not clear how to use them.

// eslint-disable-next-line
//! It seems like (according to SimpleTuts YouTube video) within the providers folder you may also include the reducer switch statement with the action type and different states in it! Then you feed that to the provider...
//! In our examples we have the reducer within our _state folder...

// eslint-disable-next-line
//! THEN according ot SimpleTuts, you take the initialState data from the provider and cut and paste it INSTEAD in the reducer which is in our _state folder...

//! THEN you go ahead and spread it into the provider !
